# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.

from . import analytic
from . import account_move
from . import account_move_line
from . import chart_template
from . import crm_team
from . import ir_config_parameter
from . import payment_provider
from . import payment_transaction
from . import product_category
from . import product_document
from . import product_product
from . import product_template
from . import res_company
from . import res_partner
from . import sale_order
from . import sale_order_line
from . import utm_campaign
from . import oms_promotion
from . import oms_special_price
from . import oms_price_list
from . import oms_taxgroup
from . import oms_sync_job
from . import oms_product_group
from . import oms_product_item
from . import oms_customer
from . import oms_promotion_product_category
from . import oms_approval_workflow
from . import oms_payment_terms
from . import oms_prjinfo
from . import oms_warehouse
from . import oms_marketing_campaign
from . import oms_sales_blanket_agreement
from . import res_users
from . import oms_warehouse_order_preparation
from . import oms_inventory
from . import oms_transport
from . import oms_group_price_list
from . import oms_qr_payment_wizard
from . import oms_pricelist_frame
from . import res_config_settings_auto_purchase_promo
from . import sale_order_auto_purchase_promo
from . import oms_customer_pricelist
from . import product_pricelist